### ISSUE TITLE
Show your widgets!

### ISSUE THREAD

**Issue by fr500** [vurtun/nuklear#349]
I'm working on an android style interface, so I'm doing some custom widgets and I thought a showoff thread would be nice...

I'm just getting started so:

![image](https://cloud.githubusercontent.com/assets/1721040/23190875/9b30a8a6-f868-11e6-9a9f-23f6c6808cf6.png)

**Comment by ventosus** [comment]
Here a UI for an audio plugin I'm working on, with syntax hilighting and custom dial widgets.

https://open-music-kontrollers.ch/lv2/moony/moony_screeny.png

**Comment by dumblob** [comment]
Impressive work! Will you then publish your work and add a link here? Are you using something like Cassowary (see https://github.com/vurtun/nuklear/issues/123#issuecomment-260666623 ) for placement?

By the way, there is already a thread for screenshots: https://github.com/vurtun/nuklear/issues/202 .

**Comment by ventosus** [comment]
> Will you then publish your work and add a link here?

https://github.com/OpenMusicKontrollers/moony.lv2

> Are you using something like Cassowary (see #123 (comment) ) for placement?

No, stock nuklear with a slightly modified nk_text_edit with hooks for character index based coloring for syntax hilighting.

**Comment by fr500** [comment]
@dumblob oh sorry I didn't see the thread...

**Comment by vurtun** [comment]
@fr500 @ventosus this made my day. Looks quite amazing. @fr500 as for sidebar gamepad control why not just use an index to store currently active component since the sidebar is fixed and just increment/decrement on up/down. As for left/right you could just switch between sidebar and main window focus.

**Comment by fr500** [comment]
@vurtun, yeah I haven't hooked GLFW inputs yet at all so I haven't tested but I guess following the example you made for me back when it was zahnrad it should be possible.

I was thinking about having two indexes to allow easy navigation between both panels.
I'm just designing the components atm. Nothing is functional other than hover and click changing color :p

**Comment by fr500** [comment]
@vurtun, I have a question now that I have you here.
I have this section

```
      nk_begin(ctx, "History", nk_rect(WINDOW_WIDTH * 30 / 100 + 1, 0, WINDOW_WIDTH * 70 / 100, WINDOW_HEIGHT), 0);
      { 
         set_style(ctx);

         content_title(ctx, "History", &fonts[6]);
         nk_layout_row_dynamic(ctx, 280, 4);
         content_entry(ctx, "Super Metroid", "Super Nintendo Entertainment System", &fonts[2], &fonts[1], test_entry, test);
         content_entry(ctx, "Label 2", "Sublabel 2", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label 3", "Sublabel 3", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label 4", "Sublabel 4", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label 5", "Sublabel 5", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label 6", "Sublabel 6", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label 7", "Sublabel 7", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label 8", "Sublabel 8", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label 9", "Sublabel 9", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label a", "Sublabel a", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label b", "Sublabel b", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label c", "Sublabel c", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label d", "Sublabel d", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label e", "Sublabel e", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label f", "Sublabel f", &fonts[2], &fonts[1], color_bars, test);
         content_entry(ctx, "Label g", "Sublabel g", &fonts[2], &fonts[1], color_bars, test);

         set_style(ctx);
      }
      nk_end(ctx);
```

it works fine, it even shows the scrollbar for the items that draw partially off screen, looks like this:

![image](https://cloud.githubusercontent.com/assets/1721040/23241971/754c854c-f944-11e6-8a0e-ad978d5b983b.png)

But if I draw anything after this last section it just crashes. Even a tiny label so I guess it doesn't like to draw anything "off window" bounds?

I can't even get a trace since it doesn't crash, it only terminates:

> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.
> 

If I make the window... 10x the height it doesn't crash but I don't get a scrollbar then of course...
I guess a solution would be to have a container inside the window, that would always start drawing "on-screen"

**Comment by fr500** [comment]
Meh sorry for the noise I fixed it and the result seems faster and better suited to my workflow.
I guess custom widgets is way to go!

![image](https://cloud.githubusercontent.com/assets/1721040/23244993/2070c21e-f957-11e6-8d38-807ebacf1981.png)

**Comment by cxong** [comment]
I'm using nuklear in the character editor for [C-Dogs SDL](https://cxong.github.io/cdogs-sdl/):

![cdogs_nuklear_char_editor](https://cloud.githubusercontent.com/assets/1083215/25302543/d7b14aa2-2783-11e7-846d-b5ff5d45279b.gif)

Overall nuklear was very good; only problem was that to do custom widgets (the nk_combo with custom images), I had to copy a lot of nuklear functions until I get to the part containing draw calls. It would have been easier if nuklear had a way of customising all the drawing using a struct of callbacks. I also would have loved an SDL2 renderer backend but I guess that's not a very popular use case.

**Comment by fr500** [comment]
Trying to move forward with my GUI (I attempt this once every few months :) )

Now I'm trying a different approach, trying to build a toolkit on top of nuklear this time that provides me with the different views and helpers I may require so I may reuse them in different projects

Also playing with different typefaces and sizes, 
The "Select File" window is what I'm actually gonna implement here, the others are basically a theme editor.

![image](https://user-images.githubusercontent.com/1721040/32402703-097e6854-c0f8-11e7-8ee7-9e11deadc969.png)

![image](https://user-images.githubusercontent.com/1721040/32402708-156012bc-c0f8-11e7-8c86-1d96d6ec14d7.png)

A bit OT, but is there any way to have a window always on top?

**Comment by fr500** [comment]
Almost done with my theme editor, it can save and load themes from file.
It was a lot of boilerplate code but it turned out nicely

![image](https://user-images.githubusercontent.com/1721040/32417388-e8d505c4-c226-11e7-84c7-bdad026a91ec.png)

![image](https://user-images.githubusercontent.com/1721040/32417393-05bcc4ba-c227-11e7-8d8c-5307d6800358.png)

**Comment by outpoints** [comment]
@fr500 could you make that public?
I'd love to take a look at it!
I'm still getting the hang of nuklear :)

**Comment by PramUkesh** [comment]
@fr500 
Where can i find source code

**Comment by fr500** [comment]
I never finished it and I don't have it anymore

**Comment by X-death25** [comment]
@fr500 
Did you have find your source code ?
I want to look  it too
Thanks

**Comment by fr500** [comment]
Sure... 
I mean, it's just a pile of hacks 🤣 
https://git.polygoncorp.com/radius/simpleton
https://git.polygoncorp.com/radius/atv_menu
